server:
  port: 8083

spring:
  application:
    name: PAYEE-SERVICE

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: scott
    password: tiger
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.120.168.253:8761/eureka/
  instance:
    hostname: localhost

